use cargo_metadata::MetadataCommand;
use std::env;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    // Cargo.toml が変更されたら build.rs を再実行させる
    println!("cargo:rerun-if-changed=Cargo.toml");

    // カレントプロジェクトの Cargo メタデータを取得
    let metadata = MetadataCommand::new()
        .exec()
        .expect("Failed to parse cargo metadata");

    let root_pkg = metadata
        .root_package()
        .expect("Root package not found in metadata");

    // 1. [package.metadata.plugin.prefix] からプレフィックスを取得 (デフォルト値をフォールバックに指定)
    let prefix = root_pkg
        .metadata
        .get("plugin")
        .and_then(|p| p.get("prefix"))
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| format!("{}-plugin-", root_pkg.name));

    // 2. [dependencies] から prefix にマッチするクレートを抽出
    let mut plugins = Vec::new();
    for dep in &root_pkg.dependencies {
        if dep.name.starts_with(&prefix) {
            let crate_name = dep.name.replace('-', "_");
            plugins.push(crate_name);
        }
    }

    // 3. OUT_DIR 内の generated_plugins.rs へ書き出し
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest_path = out_dir.join("generated_plugins.rs");
    let mut file = File::create(dest_path).unwrap();

    writeln!(file, "// Auto-generated by build.rs. Do not edit.").unwrap();
    for plugin in plugins {
        // 先ほど確認した通り pub なしの use ... as _; を出力
        writeln!(file, "use {} as _;", plugin).unwrap();
    }
}
